### PR TITLE
Cleanups and order

### PR DESCRIPTION
**Pull request by runcom**
@mrunalp see each individual commit - this isn't changing any behavior, just moves things around

### CODE REVIEW

**Comment by mikebrow** [comment]
LGTM
Liked the changes.. esp `/s/pullimage/image pull/` making it consistent with the command/subcommand cli model.

**Comment by mrunalp** [comment]
@runcom This should be independent of #43 right?

**Comment by mrunalp** [comment]
pod status seg faulted with this PR :/ Probably needs rebase.

**Comment by runcom** [comment]
@mrunalp rebased

**Comment by mrunalp** [comment]
Alright, I'll retest this first.

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
