### PR TITLE
Check if container in a pod is already stopped before stopping it

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
Actually, we don't want to refresh status here. I'll fixup the PR.

**Comment by mrunalp** [comment]
Fixed.

**Comment by runcom** [comment]
LGTM

**Comment by mrunalp** [comment]
okay, travis is running here now :)

**Comment by mrunalp** [comment]
@runcom 
```
$ make lint
checking lint
WARNING: deadline exceeded by linter errcheck on ./cmd/server (try increasing --deadline)
WARNING: deadline exceeded by linter interfacer on ./cmd/server (try increasing --deadline)
WARNING: deadline exceeded by linter structcheck on ./cmd/server (try increasing --deadline)
WARNING: deadline exceeded by linter varcheck on ./cmd/server (try increasing --deadline)
WARNING: deadline exceeded by linter unconvert on ./cmd/server (try increasing --deadline)
make: *** [lint] Error 2
The command "make lint" exited with 2.
```

**Comment by runcom** [comment]
@mrunalp should be just a setting to tune in .tool/lint

**Comment by mrunalp** [comment]
@runcom okay, I'll take a look in a bit.

**Comment by mrunalp** [comment]
opened #40 let's see.

**Comment by runcom** [comment]
Rebase then I merge?

**Comment by mrunalp** [comment]
Rebased.

**Comment by runcom** [comment]
LGTM

**Pull request merged**
