### PR TITLE
Fixes to the Makefile

### PR DESCRIPTION
**Pull request by mrunalp**
`--update` is ignored in gometalinter now.
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
yup yup yup :smile:

**Comment by runcom** [comment]
Wait, has Travis been triggered or not here?!

**Comment by mrunalp** [comment]
@runcom I did not see Travis :/ I will check with @vishh

**Comment by vishh** [comment]
I verified that travis is enabled. Can you try again @mrunalp

**Comment by mrunalp** [comment]
Thanks! It is working now 😃

**Pull request merged**
