### PR TITLE
Remove "compliant" from README

### PR DESCRIPTION
**Pull request by mrunalp**
@sarahnovotny PTAL

cc: @runcom to address some concerns raised in #12 

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
Sounds good to me

**Comment by runcom** [comment]
@sarahnovotny happy to merge after your ACK

**Comment by sarahnovotny** [comment]
@mrunalp did you reach out to the TMB?  It's not only the compliance piece, but the use of OCI that we need to have guidance about.

**Comment by mrunalp** [comment]
@sarahnovotny I have reached out to Rob Dolin about these concerns. I will let you know once I hear back. I am fine changing the name of the project if required. Thanks!

**Comment by mrunalp** [comment]
Merging this to take out `compliant`.

**Pull request merged**
