### PR TITLE
*: switch from godep to glide

### PR DESCRIPTION
**Pull request by runcom**
Half the vendor size should be gone and it's less error prone to use glide than godep

@cyphar could you try this patch and see if it solves #18 ?

@mrunalp I don't know how you feel about this but using godep is a real pain since it depends on your own gopath instead of fetching new revisions.

This patch also adds an handly `make update-deps` which works like a charm and that's what we use in opencontainers/image-spec and opencontainers/image-tool

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
Needs rebase now. Also, I'll wait for test results from @cyphar to see if fixes his issues. Thanks!

**Comment by runcom** [comment]
@mrunalp rebased - I hope this fixes @cyphar's issue otherwise it could be a golang issue as he pointed out in #18. Regardless I hope to get this in soon :P can't stand godep anymore

**Comment by mrunalp** [comment]
@runcom Okay, I just tested the builds with this and it works fine :) LGTM

**Comment by cyphar** [comment]
That was quick. As an aside, I suggested using https://github.com/LK4D4/vndr since it is a no-nonsense dumb vendoring tool without any magic (though I haven't used glide before, so maybe it's the same thing?).

**Comment by runcom** [comment]
> That was quick. As an aside, I suggested using https://github.com/LK4D4/vndr since it is a no-nonsense dumb vendoring tool without any magic (though I haven't used glide before, so maybe it's the same thing?).

glide isn't really so dump but it's imo more powerful

**Pull request merged**
